{
 "title": "URL Frontier",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Outgoing URLs per sec",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(frontier_getURLs_total{instance=~\"$instance\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Incoming URLs per sec",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(frontier_putURLs_total{instance=~\"$instance\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Put URLs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(frontier_putURLs_completed_total{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Completed"
    },
    {
     "expr": "increase(frontier_putURLs_discovered_total{instance=~\"$instance\", discovered=\"false\"}[$__interval])",
     "legendFormat": "Known"
    },
    {
     "expr": "increase(frontier_putURLs_discovered_total{instance=~\"$instance\", discovered=\"true\"}[$__interval])",
     "legendFormat": "Discovered"
    },
    {
     "expr": "increase(frontier_putURLs_ignored_total{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Ignored"
    },
    {
     "expr": "increase(frontier_putURLs_total{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Get URLs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(frontier_getURLs_total{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "URLs sent"
    },
    {
     "expr": "increase(frontier_getURLs_latency_seconds_sum{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "latency call getURLs"
    }
   ]
  },
  {
   "title": "Method calls",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(frontier_getURLs_calls_total{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "putURLs"
    },
    {
     "expr": "increase(frontier_putURLs_calls_total{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "getURLs"
    }
   ]
  }
 ]
}